### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1289821102 for 330e63970295cc41808c887e22c439e12be8aab3

https://gitlab.com/MatrixAI/open-source/js-events/-/pipelines/1289821102

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1289833462 for ff67b30ddc953eb368302d14069956920f0f0bbf

https://gitlab.com/MatrixAI/open-source/js-events/-/pipelines/1289833462

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1289837926 for 9de0ee517f8847eeb8c71e65cb47c4e22872903e

https://gitlab.com/MatrixAI/open-source/js-events/-/pipelines/1289837926

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1289842859 for 34e41e0dda1fd6df1cd406b97d4593a660613886

https://gitlab.com/MatrixAI/open-source/js-events/-/pipelines/1289842859

**Comment by CMCDragonkai** [comment]
@MatrixAI/matrixai-engineers releasing 4.0.0 from this.

Also note that with node v20, there is no more need for `.npmrc`, it appears to be automatic.

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 1289837926 for 9de0ee517f8847eeb8c71e65cb47c4e22872903e

https://gitlab.com/MatrixAI/open-source/js-events/-/pipelines/1289837926

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 1289842859 for 34e41e0dda1fd6df1cd406b97d4593a660613886

https://gitlab.com/MatrixAI/open-source/js-events/-/pipelines/1289842859

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1289878370 for 382a4d87e6bf852fe1869c664ee80ff2c4e76eb4

https://gitlab.com/MatrixAI/open-source/js-events/-/pipelines/1289878370

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 1289878370 for 382a4d87e6bf852fe1869c664ee80ff2c4e76eb4

https://gitlab.com/MatrixAI/open-source/js-events/-/pipelines/1289878370

**Pull request merged**
